name: Set-up toolchain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout toolchain
      uses: actions/checkout@v2

    - name: Install Ninja
      run: choco install ninja --confirm
      shell: pwsh

    - name: Clone ngage-toolchain
      run: git clone https://github.com/ngagesdk/ngage-toolchain.git

    - name: Set up NGAGESDK environment variable
      run: |
        $ngagesdk = "${{ github.workspace }}/ngage-toolchain"
        $ngagesdk = $ngagesdk -replace '\\', '/'
        echo "NGAGESDK=$ngagesdk" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Add runtime paths to PATH
      run: |
        echo "${{ env.NGAGESDK }}/sdk/sdk/6.1/Shared/EPOC32/gcc/bin" >> $env:GITHUB_PATH
        echo "${{ env.NGAGESDK }}/sdk/sdk/6.1/Shared/EPOC32/ngagesdk/bin" >> $env:GITHUB_PATH
      shell: pwsh

    - name: Verify directory structure
      run: |
        echo "NGAGESDK: ${{ env.NGAGESDK }}"
        ls ${{ env.NGAGESDK }}
        ls ${{ env.NGAGESDK }}/setup
      shell: pwsh

    - name: Fetch SDK
      run: cmake -G "Ninja" -S ${{ env.NGAGESDK }}/setup -B ${{ env.NGAGESDK }}/build
      shell: pwsh

    - name: Build Celeste
      run: |
        cmake -G "Ninja" -S ${{ env.NGAGESDK }}/projects/celeste -B ${{ env.NGAGESDK }}/projects/celeste/build -DBUILD_CI_WORKFLOW=ON -DCMAKE_TOOLCHAIN_FILE=${{ env.NGAGESDK }}/cmake/ngage-toolchain.cmake
        cmake --build ${{ env.NGAGESDK }}/projects/celeste/build
      shell: pwsh

    - name: Clone Simple DirectMedia Layer 3
      run: git clone -b nokia_ngage https://github.com/ngagesdk/SDL.git

    - name: Build Simple DirectMedia Layer 3
      run: |
        cmake -G "Ninja" -S SDL -B SDL/build -DBUILD_FOR_NOKIA_NGAGE=ON -DCMAKE_TOOLCHAIN_FILE=${{ env.NGAGESDK }}/cmake/ngage-toolchain.cmake
        cmake --build SDL/build
