name: Set-up toolchain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout toolchain
      uses: actions/checkout@v2

    - name: Set up NGAGESDK environment variable
      run: echo "NGAGESDK=$(pwd)/ngage-toolchain" >> $GITHUB_ENV

    - name: Add runtime paths to PATH
      run: |
        echo "%NGAGESDK%/sdk/sdk/6.1/Shared/EPOC32/gcc/bin" >> $GITHUB_PATH
        echo "%NGAGESDK%/sdk/sdk/6.1/Shared/EPOC32/ngagesdk/bin" >> $GITHUB_PATH

    - name: Clone ngage-toolchain
      run: git clone https://github.com/ngagesdk/ngage-toolchain.git

    - name: Fetch SDK
      run: cmake -S ${{ env.NGAGESDK }}/setup -B ${{ env.NGAGESDK }}/build
