name: Set-up toolchain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout toolchain
      uses: actions/checkout@v2

    - name: Clone ngage-toolchain
      run: git clone https://github.com/ngagesdk/ngage-toolchain.git

    - name: Set up NGAGESDK environment variable
      run: |
        $ngagesdk = "$(pwd)/ngage-toolchain"
        $ngagesdk = $ngagesdk -replace '\\', '/'
        echo "NGAGESDK=$ngagesdk" >> $env:GITHUB_ENV

    - name: Add runtime paths to PATH
      run: |
        echo "${{ env.NGAGESDK }}/sdk/sdk/6.1/Shared/EPOC32/gcc/bin" >> $env:GITHUB_PATH
        echo "${{ env.NGAGESDK }}/sdk/sdk/6.1/Shared/EPOC32/ngagesdk/bin" >> $env:GITHUB_PATH
      env:
        NGAGESDK: ${{ github.workspace }}/ngage-toolchain

    - name: Verify directory structure
      run: |
        echo "NGAGESDK: ${{ env.NGAGESDK }}"
        ls ${{ env.NGAGESDK }}
        ls ${{ env.NGAGESDK }}/setup
      env:
        NGAGESDK: ${{ github.workspace }}/ngage-toolchain

    - name: Fetch SDK
      run: cmake -S ${{ env.NGAGESDK }}/setup -B ${{ env.NGAGESDK }}/build
      env:
        NGAGESDK: ${{ github.workspace }}/ngage-toolchain
